// Code generated by "stringer -type=LogLevel"; DO NOT EDIT.

package app

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TRACE-1]
	_ = x[DEBUG-2]
	_ = x[USER-4]
	_ = x[INFO-8]
	_ = x[ERROR-16]
	_ = x[SYSTEM-32]
	_ = x[NONE-64]
}

const (
	_LogLevel_name_0 = "TRACEDEBUG"
	_LogLevel_name_1 = "USER"
	_LogLevel_name_2 = "INFO"
	_LogLevel_name_3 = "ERROR"
	_LogLevel_name_4 = "SYSTEM"
	_LogLevel_name_5 = "NONE"
)

var (
	_LogLevel_index_0 = [...]uint8{0, 5, 10}
)

func (i LogLevel) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _LogLevel_name_0[_LogLevel_index_0[i]:_LogLevel_index_0[i+1]]
	case i == 4:
		return _LogLevel_name_1
	case i == 8:
		return _LogLevel_name_2
	case i == 16:
		return _LogLevel_name_3
	case i == 32:
		return _LogLevel_name_4
	case i == 64:
		return _LogLevel_name_5
	default:
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
